from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from services.ai_service import generate_learning_roadmap
from services.resource_service import fetch_resources_for_query

router = APIRouter(tags=["generation"])

class PathRequest(BaseModel):
    """
    Updated schema tracking daily user availability intervals instead of absolute project lengths.
    """
    topic: str
    experience_level: str
    hours_per_day: int

@router.post("/generate")
def create_path(request: PathRequest):
    """
    Processes incoming configuration values, calls the dynamic timeline service,
    injects live resources, and returns structured object data.
    """
    # 1. Request base JSON roadmap object structure from Azure OpenAI
    roadmap_data = generate_learning_roadmap(
        topic=request.topic,
        hours_per_day=request.hours_per_day,
        level=request.experience_level
    )

    # 2. Immediately intercept service-level failures
    if "error" in roadmap_data:
        raise HTTPException(status_code=500, detail=roadmap_data["error"])

    # 3. Loop through each week generated by the AI model (Now properly nested inside the function!)
    for week in roadmap_data.get("weeks", []):
        week_resources = []

        # Extract the specialized search queries provided by the AI
        queries = week.get("search_queries", [])

        # Call the link resolution helper for each query string
        for query in queries:
            fetched_links = fetch_resources_for_query(query)
            week_resources.extend(fetched_links)

        # Inject the final compiled resources array directly into the week node
        week["live_resources"] = week_resources

        # Pop the temporary search queries from the object payload so it stays completely clean
        week.pop("search_queries", None)

    # 4. Return the fully enhanced, structured JSON data back down the wire
    return roadmap_data